#!/usr/bin/env sh
set -meu

PORT=${PORT:-80}
CLOUD_RUN="${CLOUD_RUN:-}"

# Nginx doesn't support env variables, so we'll just overwrite the config before running Nginx...
sed -i "s/listen 80;/listen ${PORT};/g" /etc/nginx/sites-enabled/default

# If on Google Cloud Run
if [ "$CLOUD_RUN" ]; then
    mv /usr/local/etc/php/conf.d/zz-php.cloudrun.ini.disabled /usr/local/etc/php/conf.d/zz-php.cloudrun.ini
fi

# Catch signals and kill the sub-processes, giving them a chance to clean-up
trap 'kill -INT %1; kill -INT %2; sleep 5; exit' INT TERM
inotifywait -e create,moved_to,attrib /tmp/php-fpm \
    && { echo 'starting Nginx...'; nginx -g 'daemon off;'; echo 'exited Nginx'; } &
php-fpm &

wait
